feat: Add hidden_fields in context
stone-payments/kong-plugin-template-transformer pull request #116
Opened 2020-09-22 16:50 UTC by jessicapaz

Add hidden fields in context so we can use in others plugins.

2020-09-22 16:56 UTC, PFadel requested changes

2020-09-22 16:56 UTC, PFadel commented on template-transformer/handler.lua
> +
Por que isso precisa ser adicionado aqui nesse plugin se não está sendo usado aqui ?

2020-09-22 16:58 UTC, jessicapaz commented on template-transformer/handler.lua
> +
Esse plugin já usa os hidden_fields pra logar body de request, só tô colocando ele no context data pra poder usar esses campos em outro plugin também.

2020-09-24 14:32 UTC, PFadel approved these changes

2020-09-24 15:44 UTC, jonathanlazaro1 approved these changes

2020-09-24 16:00 UTC, merged