ci: Update secret name
stone-payments/kong-plugin-template-transformer pull request #142
Opened 2021-12-27 19:21 UTC by GilbertoVGL

2021-12-27 19:23 UTC, Wuerike submitted a review, later dismissed

2021-12-27 20:00 UTC, leoferlopes commented on .github/workflows/publish.yml
> +          credentials_json: ${{ secrets.gcp_credentials }}
era maiusculo mesmo

2021-12-27 20:04 UTC, leoferlopes requested changes

2021-12-27 20:04 UTC, leoferlopes commented on .github/workflows/publish.yml
>          uses: google-github-actions/get-secretmanager-secrets@v0.2.2
aqui você precisa declarar um id pra usar o secret depois:
```suggestion
        uses: google-github-actions/get-secretmanager-secrets@v0.2.2
        id: luarocks-credentials
```


pra usar o secret: 
`${{ steps.luarocks-credentials.outputs.LUAROCKS_API_KEY }}`

2021-12-28 11:54 UTC, andremacdowell approved these changes

2022-01-03 14:07 UTC, Wuerike approved these changes

2022-01-03 15:27 UTC, leoferlopes approved these changes

2022-01-03 15:27 UTC, merged